### ISSUE TITLE
FYI: must save quarto-publish.yml as quarto_publish.yml

### ISSUE THREAD

**Issue by TheresaBurnham** [Openscapes/quarto-website-tutorial#26]
In following this tutorial, the initial rendering failed because  it was searching for a _publish.yml file, not -publish.yml. I changed the dash to underscore and was successful. 

Also, there is now a different source/branch convention on the GitHub Pages page. You first select "Deploy from a Branch" in the source and then select the branch/root. 

Not a major issue, flagging just in case!

**Comment by jules32** [comment]
Hi, thank you for this feedback, it is much appreciated! We will be able to address this next month, along with #25. Thanks again :)

**Comment by stefaniebutland** [comment]
Hi @TheresaBurnham. I'm part of the Openscapes team. Thank you for opening this issue. I'm reproducing this and then will update the documentation. I have a couple of questions for you.

- which method did you use: [fork](https://openscapes.github.io/quarto-website-tutorial/explore.html#fork-to-your-account) or [download](https://openscapes.github.io/quarto-website-tutorial/explore.html#download-instead-of-fork)?
- when you renamed quarto-publish.yml as quarto_publish.yml, do you recall if the entire quarto-website-tutorial appeared? asking since when I first tested, only the README was rendered ... aha! Issue #25 addresses this.

Thank you!

**Comment by TheresaBurnham** [comment]
Hi Stefanie - 
1. I downloaded the repository
2. I can't remember the exact outputs from the renaming! But I was able to follow the rest of the tutorial no problem. 

Thanks!

**Comment by stefaniebutland** [comment]
Thank you @TheresaBurnham. I'll ping here when it's updated

**Comment by stefaniebutland** [comment]
We've (finally) updated the tutorial. With testing updated instructions, I found that `quarto-publish.yml` filename will work. Thank you again for reporting this and don't hesitate to open a new issue for any problems!
